// packages/vue-components/src/PassageEditor.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import type { Passage } from '@writewhisker/story-models';

export interface PassageEditorProps {
  passage: Passage;
}

export interface PassageEditorEmits {
  (e: 'update:passage', passage: Passage): void;
}

const props = defineProps<PassageEditorProps>();
const emit = defineEmits<PassageEditorEmits>();

const title = ref(props.passage.title);
const content = ref(props.passage.content);

watch([title, content], () => {
  emit('update:passage', {
    ...props.passage,
    title: title.value,
    content: content.value,
  });
});
</script>

<template>
  <div class="passage-editor">
    <div class="editor">
      <div class="field">
        <label>Title</label>
        <input
          v-model="title"
          type="text"
          placeholder="Passage title"
        />
      </div>

      <div class="field">
        <label>Content</label>
        <textarea
          v-model="content"
          placeholder="Passage content"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
.passage-editor {
  font-family: system-ui, sans-serif;
}

.editor {
  padding: 1rem;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.field {
  margin-bottom: 1rem;
}

label {
  display: block;
  margin-bottom: 0.25rem;
  font-weight: 600;
  color: #333;
}

input,
textarea {
  width: 100%;
  padding: 0.5rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-family: inherit;
}

textarea {
  min-height: 200px;
  resize: vertical;
}
</style>

// packages/passage-editor/src/PassageEditor.svelte
<script lang="ts">
  import type { PassageData, EditorOptions } from './types';

  interface Props {
    passage?: PassageData;
    options?: EditorOptions;
    onChange?: (passage: PassageData) => void;
  }

  let {
    passage = { id: '', title: '', content: '', tags: [] },
    options = {},
    onChange
  }: Props = $props();

  let localPassage = $state({ ...passage });

  function handleTitleChange(e: Event) {
    const target = e.target as HTMLInputElement;
    localPassage.title = target.value;
    onChange?.(localPassage);
  }

  function handleContentChange(e: Event) {
    const target = e.target as HTMLTextAreaElement;
    localPassage.content = target.value;
    onChange?.(localPassage);
  }
</script>

<div class="passage-editor">
  <div class="header">
    <input
      type="text"
      class="title-input"
      placeholder="Passage Title"
      value={localPassage.title}
      oninput={handleTitleChange}
    />
    <div class="tags">
      {#each localPassage.tags as tag}
        <span class="tag">{tag}</span>
      {/each}
    </div>
  </div>

  <div class="content-editor">
    <textarea
      class="content-input"
      placeholder="Write your passage content here..."
      value={localPassage.content}
      oninput={handleContentChange}
      spellcheck={options.spellcheck ?? true}
    ></textarea>
  </div>

  <div class="footer">
    <span class="word-count">
      {localPassage.content.split(/\s+/).filter(w => w.length > 0).length} words
    </span>
  </div>
</div>

<style>
  .passage-editor {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: white;
    border: 1px solid #ddd;
    border-radius: 8px;
  }

  .header {
    padding: 16px;
    border-bottom: 1px solid #ddd;
  }

  .title-input {
    width: 100%;
    padding: 8px;
    font-size: 18px;
    font-weight: 600;
    border: 1px solid #ddd;
    border-radius: 4px;
  }

  .tags {
    display: flex;
    gap: 8px;
    margin-top: 8px;
  }

  .tag {
    padding: 4px 12px;
    background: #e5e7eb;
    border-radius: 12px;
    font-size: 12px;
  }

  .content-editor {
    flex: 1;
    padding: 16px;
  }

  .content-input {
    width: 100%;
    height: 100%;
    padding: 12px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-family: 'Consolas', 'Monaco', monospace;
    font-size: 14px;
    line-height: 1.6;
    resize: none;
  }

  .footer {
    padding: 8px 16px;
    border-top: 1px solid #ddd;
    font-size: 12px;
    color: #666;
    text-align: right;
  }
</style>
