// packages/react-components/src/PassageEditor.tsx
/**
 * Passage Editor Component
 */

import { useState, useCallback } from 'react';
import type { Passage } from '@writewhisker/story-models';

export interface PassageEditorProps {
  passage: Passage;
  onChange?: (passage: Passage) => void;
  className?: string;
  style?: React.CSSProperties;
}

export function PassageEditor({ passage: initialPassage, onChange, className, style }: PassageEditorProps) {
  const [passage, setPassage] = useState<Passage>(initialPassage);

  const handleTitleChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const updated = { ...passage, title: e.target.value };
    setPassage(updated);
    onChange?.(updated);
  }, [passage, onChange]);

  const handleContentChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const updated = { ...passage, content: e.target.value };
    setPassage(updated);
    onChange?.(updated);
  }, [passage, onChange]);

  return (
    <div className={className} style={{ fontFamily: 'system-ui, sans-serif', ...style }}>
      <div style={{ padding: '1rem', border: '1px solid #ddd', borderRadius: '4px' }}>
        <div style={{ marginBottom: '1rem' }}>
          <label style={{ display: 'block', marginBottom: '0.25rem', fontWeight: 600, color: '#333' }}>
            Title
          </label>
          <input
            type="text"
            value={passage.title}
            onChange={handleTitleChange}
            style={{
              width: '100%',
              padding: '0.5rem',
              border: '1px solid #ddd',
              borderRadius: '4px',
              fontFamily: 'inherit',
            }}
          />
        </div>

        <div style={{ marginBottom: '1rem' }}>
          <label style={{ display: 'block', marginBottom: '0.25rem', fontWeight: 600, color: '#333' }}>
            Content
          </label>
          <textarea
            value={passage.content}
            onChange={handleContentChange}
            style={{
              width: '100%',
              minHeight: '200px',
              padding: '0.5rem',
              border: '1px solid #ddd',
              borderRadius: '4px',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
        </div>
      </div>
    </div>
  );
}

// packages/vue-components/src/PassageEditor.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import type { Passage } from '@writewhisker/story-models';

export interface PassageEditorProps {
  passage: Passage;
}

export interface PassageEditorEmits {
  (e: 'update:passage', passage: Passage): void;
}

const props = defineProps<PassageEditorProps>();
const emit = defineEmits<PassageEditorEmits>();

const title = ref(props.passage.title);
const content = ref(props.passage.content);

watch([title, content], () => {
  emit('update:passage', {
    ...props.passage,
    title: title.value,
    content: content.value,
  });
});
</script>

<template>
  <div class="passage-editor">
    <div class="editor">
      <div class="field">
        <label>Title</label>
        <input
          v-model="title"
          type="text"
          placeholder="Passage title"
        />
      </div>

      <div class="field">
        <label>Content</label>
        <textarea
          v-model="content"
          placeholder="Passage content"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
.passage-editor {
  font-family: system-ui, sans-serif;
}

.editor {
  padding: 1rem;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.field {
  margin-bottom: 1rem;
}

label {
  display: block;
  margin-bottom: 0.25rem;
  font-weight: 600;
  color: #333;
}

input,
textarea {
  width: 100%;
  padding: 0.5rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-family: inherit;
}

textarea {
  min-height: 200px;
  resize: vertical;
}
</style>
